# Generated by Django 5.1.3 on 2024-12-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatetable',
            old_name='user',
            new_name='candidate_id',
        ),
        migrations.RenameField(
            model_name='recruitertable',
            old_name='user',
            new_name='recruiter_id',
        ),
    ]
