# Generated by Django 5.1.3 on 2024-12-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_user_candidatetable_candidate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatetable',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='recruitertable',
            old_name='recruiter_id',
            new_name='recruiter',
        ),
    ]
