# Generated by Django 5.1.3 on 2024-12-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_applicationtable_email_applicationtable_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostingtable',
            old_name='user',
            new_name='recruiter',
        ),
    ]
