# Generated by Django 5.1.3 on 2024-12-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_rename_user_jobpostingtable_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtable',
            old_name='job_id',
            new_name='job',
        ),
    ]
