# Generated by Django 5.1.3 on 2024-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_applicationtable_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtable',
            name='is_private',
        ),
        migrations.AddField(
            model_name='jobpostingtable',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
